#!/bin/sh

set -e

[ -f /etc/default/plutono-server ] && . /etc/default/plutono-server

IS_UPGRADE=false


case "$1" in
	configure)
	[ -z "$PLUTONO_USER" ] && PLUTONO_USER="plutono"
	[ -z "$PLUTONO_GROUP" ] && PLUTONO_GROUP="plutono"
	if ! getent group "$PLUTONO_GROUP" > /dev/null 2>&1 ; then
	    addgroup --system "$PLUTONO_GROUP" --quiet
	fi
	if ! id $PLUTONO_USER > /dev/null 2>&1 ; then
	    adduser --system --home /usr/share/plutono --no-create-home \
		--ingroup "$PLUTONO_GROUP" --disabled-password --shell /bin/false \
		"$PLUTONO_USER"
	fi

	# Set user permissions on /var/log/plutono, /var/lib/plutono
	mkdir -p /var/log/plutono /var/lib/plutono
	chown -R $PLUTONO_USER:$PLUTONO_GROUP /var/log/plutono /var/lib/plutono
	chmod 755 /var/log/plutono /var/lib/plutono

  # copy user config files
  if [ ! -f $CONF_FILE ]; then
    cp /usr/share/plutono/conf/sample.ini $CONF_FILE
    cp /usr/share/plutono/conf/ldap.toml /etc/plutono/ldap.toml
  fi

  if [ ! -d $PROVISIONING_CFG_DIR ]; then
    mkdir -p $PROVISIONING_CFG_DIR/dashboards $PROVISIONING_CFG_DIR/datasources
    cp /usr/share/plutono/conf/provisioning/dashboards/sample.yaml $PROVISIONING_CFG_DIR/dashboards/sample.yaml
    cp /usr/share/plutono/conf/provisioning/datasources/sample.yaml $PROVISIONING_CFG_DIR/datasources/sample.yaml
  fi

  if [ ! -d $PROVISIONING_CFG_DIR/notifiers ]; then
    mkdir -p $PROVISIONING_CFG_DIR/notifiers
    cp /usr/share/plutono/conf/provisioning/notifiers/sample.yaml $PROVISIONING_CFG_DIR/notifiers/sample.yaml
  fi

  if [ ! -d $PROVISIONING_CFG_DIR/plugins ]; then
    mkdir -p $PROVISIONING_CFG_DIR/plugins
    cp /usr/share/plutono/conf/provisioning/plugins/sample.yaml $PROVISIONING_CFG_DIR/plugins/sample.yaml
  fi

	# configuration files should not be modifiable by plutono user, as this can be a security issue
	chown -Rh root:$PLUTONO_GROUP /etc/plutono/*
	chmod 755 /etc/plutono
	find /etc/plutono -type f -exec chmod 640 {} ';'
	find /etc/plutono -type d -exec chmod 755 {} ';'

  # If $1=configure and $2 is set, this is an upgrade
  if [ "$2" != "" ]; then
    IS_UPGRADE=true
  fi

  if [ "x$IS_UPGRADE" != "xtrue" ]; then
    if command -v systemctl >/dev/null; then
      echo "### NOT starting on installation, please execute the following statements to configure plutono to start automatically using systemd"
      echo " sudo /bin/systemctl daemon-reload"
      echo " sudo /bin/systemctl enable plutono-server"
      echo "### You can start plutono-server by executing"
      echo " sudo /bin/systemctl start plutono-server"
    elif command -v update-rc.d >/dev/null; then
      echo "### NOT starting plutono-server by default on bootup, please execute"
      echo " sudo update-rc.d plutono-server defaults 95 10"
      echo "### In order to start plutono-server, execute"
      echo " sudo service plutono-server start"
    fi
  elif [ "$RESTART_ON_UPGRADE" = "true" ]; then

    echo -n "Restarting plutono-server service..."

    if command -v systemctl >/dev/null; then
      systemctl daemon-reload
      systemctl restart plutono-server || true
    elif [ -x /etc/init.d/plutono-server ]; then
      if command -v invoke-rc.d >/dev/null; then
        invoke-rc.d plutono-server restart || true
      else
        /etc/init.d/plutono-server restart || true
      fi
    fi
    echo " OK"

	fi
	;;
esac
