#!/bin/sh

set -e

echo "POSTTRANS: Running script"

[ -f /etc/sysconfig/plutono-server ] && . /etc/sysconfig/plutono-server

# copy config files if missing
if [ ! -f /etc/plutono/plutono.ini ]; then
  echo "POSTTRANS: Config file not found"

  if [ -f /etc/plutono/plutono.ini.rpmsave ]; then
    echo "POSTTRANS: /etc/plutono/plutono.ini.rpmsave config file found."
    mv /etc/plutono/plutono.ini.rpmsave /etc/plutono/plutono.ini
    echo "POSTTRANS: /etc/plutono/plutono.ini restored"

    if [ -f /etc/plutono/ldap.toml.rpmsave ]; then
      echo "POSTTRANS: /etc/plutono/ldap.toml.rpmsave found"
      mv /etc/plutono/ldap.toml.rpmsave /etc/plutono/ldap.toml
      echo "POSTTRANS: /etc/plutono/ldap.toml restored"
    fi

    echo "POSTTRANS: Restoring config file permissions"
    chown -Rh root:$PLUTONO_GROUP /etc/plutono/*
    chmod 755 /etc/plutono
    find /etc/plutono -type f -exec chmod 640 {} ';'
    find /etc/plutono -type d -exec chmod 755 {} ';'
  fi
fi


