#!/bin/sh

set -e

[ -f /etc/sysconfig/plutono-server ] && . /etc/sysconfig/plutono-server

startPlutono() {
  if [ -x /bin/systemctl ] ; then
    /bin/systemctl daemon-reload
		/bin/systemctl start plutono-server.service
	elif [ -x /etc/init.d/plutono-server ] ; then
		/etc/init.d/plutono-server start
	elif [ -x /etc/rc.d/init.d/plutono-server ] ; then
		/etc/rc.d/init.d/plutono-server start
	fi
}

stopPlutono() {
	if [ -x /bin/systemctl ] ; then
		/bin/systemctl stop plutono-server.service > /dev/null 2>&1 || :
	elif [ -x /etc/init.d/plutono-service ] ; then
		/etc/init.d/plutono-service stop
	elif [ -x /etc/rc.d/init.d/plutono-service ] ; then
		/etc/rc.d/init.d/plutono-service stop
	fi
}


# Initial installation: $1 == 1
# Upgrade: $1 == 2, and configured to restart on upgrade
if [ $1 -eq 1 ] ; then
	[ -z "$PLUTONO_USER" ] && PLUTONO_USER="plutono"
	[ -z "$PLUTONO_GROUP" ] && PLUTONO_GROUP="plutono"
	if ! getent group "$PLUTONO_GROUP" > /dev/null 2>&1 ; then
    groupadd -r "$PLUTONO_GROUP"
	fi
	if ! getent passwd "$PLUTONO_USER" > /dev/null 2>&1 ; then
    useradd -r -g plutono -d /usr/share/plutono -s /sbin/nologin \
    -c "plutono user" plutono
	fi

  # copy user config files
  if [ ! -f $CONF_FILE ]; then
    cp /usr/share/plutono/conf/sample.ini $CONF_FILE
    cp /usr/share/plutono/conf/ldap.toml /etc/plutono/ldap.toml
  fi

  if [ ! -d $PROVISIONING_CFG_DIR ]; then
    mkdir -p $PROVISIONING_CFG_DIR/dashboards $PROVISIONING_CFG_DIR/datasources
    cp /usr/share/plutono/conf/provisioning/dashboards/sample.yaml $PROVISIONING_CFG_DIR/dashboards/sample.yaml
    cp /usr/share/plutono/conf/provisioning/datasources/sample.yaml $PROVISIONING_CFG_DIR/datasources/sample.yaml
  fi

  if [ ! -d $PROVISIONING_CFG_DIR/notifiers ]; then
    mkdir -p $PROVISIONING_CFG_DIR/notifiers
    cp /usr/share/plutono/conf/provisioning/notifiers/sample.yaml $PROVISIONING_CFG_DIR/notifiers/sample.yaml
  fi

  if [ ! -d $PROVISIONING_CFG_DIR/plugins ]; then
    mkdir -p $PROVISIONING_CFG_DIR/plugins
    cp /usr/share/plutono/conf/provisioning/plugins/sample.yaml $PROVISIONING_CFG_DIR/plugins/sample.yaml
  fi

 	# Set user permissions on /var/log/plutono, /var/lib/plutono
	mkdir -p /var/log/plutono /var/lib/plutono
	chown -R $PLUTONO_USER:$PLUTONO_GROUP /var/log/plutono /var/lib/plutono
	chmod 755 /var/log/plutono /var/lib/plutono

	# configuration files should not be modifiable by plutono user, as this can be a security issue
	chown -Rh root:$PLUTONO_GROUP /etc/plutono/*
	chmod 755 /etc/plutono
	find /etc/plutono -type f -exec chmod 640 {} ';'
	find /etc/plutono -type d -exec chmod 755 {} ';'

  if [ -x /bin/systemctl ] ; then
    echo "### NOT starting on installation, please execute the following statements to configure plutono to start automatically using systemd"
    echo " sudo /bin/systemctl daemon-reload"
    echo " sudo /bin/systemctl enable plutono-server.service"
    echo "### You can start plutono-server by executing"
    echo " sudo /bin/systemctl start plutono-server.service"
  elif [ -x /sbin/chkconfig ] ; then
    echo "### NOT starting plutono-server by default on bootup, please execute"
    echo " sudo /sbin/chkconfig --add plutono-server"
    echo "### In order to start plutono-server, execute"
    echo " sudo service plutono-server start"
  fi
elif [ $1 -ge 2 ] ; then
  if [ "$RESTART_ON_UPGRADE" == "true" ]; then
    stopPlutono
    startPlutono
  fi
fi
