FROM ubuntu:20.04

ARG REPO_CONFIG=plutono.list.oss
ARG PACKAGE=plutono

RUN apt update && \
    apt install -y curl                \
                   apt-transport-https \
                   ca-certificates     \
                   gnupg               && \
    curl https://packages.grafana.com/gpg.key | apt-key add -

COPY "./$REPO_CONFIG" /etc/apt/sources.list.d/plutono.list
RUN apt update && \
    apt install -y $PACKAGE
